version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_username
      - db_root_password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

secrets:
  db_root_username:
    file: ./db_root_username.txt
  db_root_password:
    file: ./db_root_password.txt

volumes:
  mongo_data:
