name: deploy-stockpikr-backend

on:
  push:
    branches: [main, cicd/pipeline]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pm2
        run: sudo npm install -g pm2

      - name: Setup ssh keys
        run: |
          mkdir -p /root/.ssh/
          echo "${{ secrets.STOCKPIKR_SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > /root/.ssh/known_hosts
          chmod 600 /root/.ssh/id_rsa

      - name: Deploy to production
        run: sudo pm2 deploy production --force

      - name: Clean up ssh keys
        run: sudo rm -rf /root/.ssh/
