name: deploy-stockpikr-backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  disabled-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is currently disabled"
      
# The original content is commented out below:

# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     strategy:
#       matrix:
#         node-version: ["20"]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install pm2
#         run: sudo npm install -g pm2
