name: Build and deploy Node.js project to Azure Function App - Stockpikr2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  disabled-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is currently disabled"

# The original content is commented out below:

# env:
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
#   NODE_VERSION: '20.x'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout GitHub Action
#         uses: actions/checkout@v4
